version: '3.7'
x-airflow-common:
    &airflow-common
    image: ${SEURON_TAG}
    restart: always
    environment:
        &airflow-common-env
        AIRFLOW__CORE__FERNET_KEY:
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
        AIRFLOW__CELERY__BROKER_URL:
        AIRFLOW__CELERY__CELERY_RESULT_BACKEND:
        AIRFLOW__WEBSERVER__SECRET_KEY:
        AIRFLOW__LOGGING__BASE_LOG_FOLDER:
        AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER:
        AIRFLOW__METRICS__STATSD_ON:
        AIRFLOW__METRICS__STATSD_HOST:
        AIRFLOW__METRICS__STATSD_PORT:
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp:/tmp



services:
    rabbitmq:
        image: rabbitmq:3.8-management
        environment:
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit heartbeat 600 consumer_timeout 2592000000
        volumes:
            - /var/lib/rabbitmq:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 60s
            retries: 5

    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
        command: -c max_connections=100 -c shared_buffers=${POSTGRES_MEM}MB
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 60s
            retries: 5

    pgbouncer:
        image: ranlu/pgbouncer:1.16.1
        environment:
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DB}
            - DB_HOST=postgres
            - MAX_CLIENT_CONN=10000
            - DEFAULT_POOL_SIZE=100
            - POOL_MODE=transaction
        ports:
            - "5432:5432"

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        environment:
            DATA_SOURCE_URI: postgres?sslmode=disable
            DATA_SOURCE_USER: ${POSTGRES_USER}
            DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}

    statsd-exporter:
        image: ranlu/statsd-exporter
        command: "--statsd.listen-udp=:9125 --web.listen-address=:9102 --statsd.mapping-config=/statsd.conf"
        ports:
            - "9102:9102"
            - "9125:9125/udp"

    prometheus:
        image: ranlu/prometheus
        ports:
            - "9090:9090"

    grafana:
        image: ranlu/grafana
        environment:
            GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
            GF_SERVER_ROOT_URL: https://localhost/grafana
            GF_USERS_DEFAULT_THEME: light
            GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/dashboards/SeuronDashboard.json
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB:
        ports:
            - "3000:3000"

    # single shot initialize the database
    init-seuronbot:
        <<: *airflow-common
        restart: on-failure
        environment:
            <<: *airflow-common-env
            DEPLOYMENT:
            ZONE:
            _AIRFLOW_DB_UPGRADE: 'true'
            _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
            _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
        command: bash pipeline/init_pipeline.sh
        deploy:
            restart_policy:
                condition: on-failure

    webserver:
        <<: *airflow-common
        command: airflow webserver
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8080/airflow/health"]
            interval: 60s
            timeout: 10s
            retries: 5
        deploy:
            restart_policy:
                condition: any

    scheduler:
        <<: *airflow-common
        command: airflow scheduler
        healthcheck:
            test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
            interval: 60s
            timeout: 10s
            retries: 5
        deploy:
            restart_policy:
                condition: any

    worker-cluster:
        <<: *airflow-common
        environment:
            <<: *airflow-common-env
            AIRFLOW__CELERY__WORKER_CONCURRENCY: 1
        command: airflow celery worker --without-gossip --without-mingle -q cluster
        deploy:
            restart_policy:
                condition: any

    worker-manager:
        <<: *airflow-common
        environment:
            <<: *airflow-common-env
            AIRFLOW__CELERY__WORKER_CONCURRENCY: 4
        command: airflow celery worker --without-gossip --without-mingle -q manager
        deploy:
            restart_policy:
                condition: any

    slackbot:
        <<: *airflow-common
        environment:
            <<: *airflow-common-env
            SLACK_TOKEN:
            DEPLOYMENT:
        command: python slackbot/slack_bot.py
        deploy:
            restart_policy:
                condition: any

    proxy:
        image: nginx:1.13.5-alpine
        restart: always
        ports:
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        deploy:
            restart_policy:
                condition: any
        #volumes:
            #- ../secrets:/run/secrets/
        command:
            sh -c "apk update && apk add apache2-utils &&
            BASIC_AUTH_PASSWORD=$$(cat /run/secrets/basic_auth_password) &&
            [ -n \"$$BASIC_AUTH_PASSWORD\" ] &&
                   AUTH_BASIC_STRING=\\\"AirflowAuthorization\\\" &&
                   htpasswd -b -c /etc/nginx/.htpasswd $$(cat /run/secrets/basic_auth_username) $${BASIC_AUTH_PASSWORD} ||
            AUTH_BASIC_STRING=off &&
            SSL_CERTIFICATE=$$(cat /run/secrets/ssl_certificate) &&
            [ -n \"$$SSL_CERTIFICATE\" ] &&
                   SSL_BLOCK=\"ssl_certificate \\/run\\/secrets\\/ssl_certificate;\\n
                    ssl_certificate_key \\/run\\/secrets\\/ssl_certificate_key;\\n
                    ssl_session_cache  builtin:1000  shared:SSL:10m;\\n
                    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;\\n
                    ssl on;\" ||
            SSL_BLOCK=\"ssl off;\" && 
            echo $$SSL_BLOCK && 
            if ! grep airflow /etc/nginx/nginx.conf; then
                sed -i -e \"s/include \\/etc\\/nginx\\/conf\\.d\\/\\*\.conf;//\" 
                -e \"\\$$s/}/
                    error_log \\/var\\/log\\/error.log;\\n
                    gzip  on;\\n
                    gzip_vary on;\\n
                    gzip_min_length 10240;\\n
                    gzip_proxied expired no-cache no-store private auth;\\n
                    gzip_types text\\/plain text\\/css text\\/xml text\\/javascript application\\/x-javascript application\\/xml;\\n
                    gzip_disable \\\"MSIE [1-6]\.\\\";\\n
                    server {\\n
                        listen 80;\\n
                        listen 443;\\n
                        auth_basic $${AUTH_BASIC_STRING};\\n
                        auth_basic_user_file \\/etc\\/nginx\\/\.htpasswd;\\n
                        $${SSL_BLOCK}\\n
                        proxy_set_header X-Real-IP \\$$remote_addr;\\n
                        proxy_set_header X-Forwarded-For \\$$proxy_add_x_forwarded_for;\\n
                        if (\\$$http_referer ~* \\\".*\\/rabbitmq\\/*.*\\\") {\\n
                            set \\$$is_rabbitmq \\\"A\\\";\\n
                        }\\n
                        if (\\$$request_uri !~* ^\\/rabbitmq\\/.*) {\\n
                            set \\$$is_rabbitmq \\\"\\$${is_rabbitmq}B\\\";\\n
                        }\\n
                        if (\\$$is_rabbitmq = AB) { \\n
                            rewrite ^\\/*(.*) \\/rabbitmq\\/\\$$1 permanent;\\n
                        }\\n
                        location \\/airflow\\/ {\\n
                            proxy_pass http:\\/\\/webserver:8080;\\n
                            proxy_set_header Host \\$$http_host;\\n
                            proxy_redirect off;\\n
                            proxy_http_version 1.1; \\n
                            proxy_set_header Upgrade \\$$http_upgrade; \\n
                            proxy_set_header Connection \\\"upgrade\\\"; \\n
                            proxy_set_header X-Forwarded-Proto \\$$scheme; \\n
                        }\\n
                        location ^~ \\/rabbitmq\\/ {\\n
                            proxy_pass http:\\/\\/rabbitmq:15672\\/;\\n
                            proxy_redirect off;\\n
                        }\\n
                    }\\n
                }/\" /etc/nginx/nginx.conf;
            fi &&
            unset BASIC_AUTH_PASSWORD &&
            unset BASIC_AUTH_USERNAME &&
            unset SSL_CERTIFICATE &&
            nginx-debug -g \"daemon off;\" 2>&1"
        secrets:
            - basic_auth_username
            - basic_auth_password
            - ssl_certificate
            - ssl_certificate_key

secrets:
    basic_auth_username:
        external: true
    basic_auth_password:
        external: true
    ssl_certificate:
        external: true
    ssl_certificate_key:
        external: true

networks:
    default:
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 10.253.0.0/16
