version: '3.3'
services:
    rabbitmq:
        image: rabbitmq:3.6.12-management-alpine
        environment:
            - RABBITMQ_ERLANG_COOKIE=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        tmpfs:
            - /var/lib
        ports:
            - "5672:5672"
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == manager ]

    postgres:
        image: mysql:5.7
        environment:
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
            - MYSQL_ROOT_PASSWORD=root_password
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == database ]
        command: --max_connections=20000 --wait-timeout=7200 --interactive-timeout=7200 --max-allowed-packet=500M --range-optimizer-max-mem-size=0 --innodb_lock_wait_timeout=7200 --innodb-rollback-on-timeout

    # single shot initialize the database
    init-db:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: on-failure
        depends_on:
            - postgres
            - rabbitmq
        environment:
            - FERNET_KEY=Z3jDcE-i0gRc7-A0ETMDUxd1MuL3Ye0tVcdDl5zmnec=
        volumes:
            # Warning mounting dags/plugins not working for autoscaler
            #- ../dags/:/usr/local/airflow/dags
            #- ../plugins:/usr/local/airflow/plugins
            #- ../config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
        #ports:
            #- "8080:8080"
        command: airflow initdb
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == database ]
        deploy:
            restart_policy:
                condition: on-failure

    webserver:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: always
        depends_on:
            - init-db
            - rabbitmq
        environment:
            - FERNET_KEY=Z3jDcE-i0gRc7-A0ETMDUxd1MuL3Ye0tVcdDl5zmnec=
        volumes:
            # Warning mounting dags/plugins not working for autoscaler
            #- ../dags/:/usr/local/airflow/dags
            #- ../plugins:/usr/local/airflow/plugins
            #- ../config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
        #ports:
            #- "8080:8080"
        command: airflow webserver
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == manager ]
            restart_policy:
                condition: any
                delay: 10m
                window: 120s

    flower:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: always
        depends_on:
            - init-db
            - rabbitmq
        #ports:
            #- "5555:5555"
        command: airflow flower
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == manager ]
            restart_policy:
                condition: any

    scheduler:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: always
        depends_on:
            - init-db
            - rabbitmq
        volumes:
            # Warning mounting dags/plugins not working for autoscaler
            #- ../dags/:/usr/local/airflow/dags
            #- ../plugins:/usr/local/airflow/plugins
            #- ../config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - FERNET_KEY=Z3jDcE-i0gRc7-A0ETMDUxd1MuL3Ye0tVcdDl5zmnec=
        command: airflow scheduler
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == manager ]
            restart_policy:
                condition: any

    visualizer:
        image: dockersamples/visualizer:stable
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        #ports:
            #- "8080:8080"
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == manager ]
            restart_policy:
                condition: any

    worker-worker:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: always
        depends_on:
            - init-db
            - rabbitmq
        volumes:
            # Warning mounting dags/plugins not working for autoscaler
            #- ../dags/:/usr/local/airflow/dags
            #- ../plugins:/usr/local/airflow/plugins
            #- ../config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
        environment:
            - FERNET_KEY=Z3jDcE-i0gRc7-A0ETMDUxd1MuL3Ye0tVcdDl5zmnec=
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
        command: airflow worker -q worker
        deploy:
            mode: global
            placement:
                constraints: [ engine.labels.infrakit-role == worker ]
            restart_policy:
                condition: any

    worker-atomic:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: always
        depends_on:
            - init-db
            - rabbitmq
        volumes:
            # Warning mounting dags/plugins not working for autoscaler
            #- ../dags/:/usr/local/airflow/dags
            #- ../plugins:/usr/local/airflow/plugins
            #- ../config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
        environment:
            - FERNET_KEY=Z3jDcE-i0gRc7-A0ETMDUxd1MuL3Ye0tVcdDl5zmnec=
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - AIRFLOW__CELERY__CELERYD_CONCURRENCY=1
        command: airflow worker -q atomic
        deploy:
            mode: global
            placement:
                constraints: [ engine.labels.infrakit-role == atomic ]
            restart_policy:
                condition: any

    worker-composite:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: always
        depends_on:
            - init-db
            - rabbitmq
        volumes:
            # Warning mounting dags/plugins not working for autoscaler
            #- ../dags/:/usr/local/airflow/dags
            #- ../plugins:/usr/local/airflow/plugins
            #- ../config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
        environment:
            - FERNET_KEY=Z3jDcE-i0gRc7-A0ETMDUxd1MuL3Ye0tVcdDl5zmnec=
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - AIRFLOW__CELERY__CELERYD_CONCURRENCY=16
        command: airflow worker -q composite
        deploy:
            mode: global
            placement:
                constraints: [ engine.labels.infrakit-role == composite ]
            restart_policy:
                condition: any

    worker-manager:
        image: ranlu/air-tasks:ranl_minnie_400
        restart: always
        depends_on:
            - init-db
            - rabbitmq
        volumes:
            # Warning mounting dags/plugins not working for autoscaler
            #- ../dags/:/usr/local/airflow/dags
            #- ../plugins:/usr/local/airflow/plugins
            #- ../config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
        environment:
            - FERNET_KEY=Z3jDcE-i0gRc7-A0ETMDUxd1MuL3Ye0tVcdDl5zmnec=
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - INFRAKIT_IMAGE
            - INFRAKIT_GROUPS_URL
        command: airflow worker -q manager
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == manager ]
            restart_policy:
                condition: any

    proxy:
        image: nginx:1.13.5-alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webserver
            - flower
            - visualizer
            - rabbitmq
        deploy:
            placement:
                constraints: [ engine.labels.infrakit-role == manager ]
            restart_policy:
                condition: any
        #volumes:
            #- ../secrets:/run/secrets/
        command:
            sh -c "apk update && apk add apache2-utils &&
            BASIC_AUTH_PASSWORD=$$(cat /run/secrets/basic_auth_password) &&
            [ -n \"$$BASIC_AUTH_PASSWORD\" ] &&
                   AUTH_BASIC_STRING=\\\"AirflowAuthorization\\\" &&
                   htpasswd -b -c /etc/nginx/.htpasswd $${BASIC_AUTH_USERNAME} $$(cat /run/secrets/basic_auth_username) ||
            AUTH_BASIC_STRING=off &&
            SSL_CERTIFICATE=$$(cat /run/secrets/ssl_certificate) &&
            [ -n \"$$SSL_CERTIFICATE\" ] &&
                   SSL_BLOCK=\"ssl_certificate \\/run\\/secrets\\/ssl_certificate;\\n
                    ssl_certificate_key \\/run\\/secrets\\/ssl_certificate_key;\\n
                    ssl_session_cache  builtin:1000  shared:SSL:10m;\\n
                    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;\\n
                    ssl on;\" ||
            SSL_BLOCK=\"ssl off;\" && 
            echo $$SSL_BLOCK && 
            if ! grep airflow /etc/nginx/nginx.conf; then
                sed -i -e \"s/include \\/etc\\/nginx\\/conf\\.d\\/\\*\.conf;//\" 
                -e \"\\$$s/}/
                    error_log \\/var\\/log\\/error.log;\\n
                    gzip  on;\\n
                    gzip_vary on;\\n
                    gzip_min_length 10240;\\n
                    gzip_proxied expired no-cache no-store private auth;\\n
                    gzip_types text\\/plain text\\/css text\\/xml text\\/javascript application\\/x-javascript application\\/xml;\\n
                    gzip_disable \\\"MSIE [1-6]\.\\\";\\n
                    server {\\n
                        listen 80;\\n
                        listen 443;\\n
                        auth_basic $${AUTH_BASIC_STRING};\\n
                        auth_basic_user_file \\/etc\\/nginx\\/\.htpasswd;\\n
                        $${SSL_BLOCK}\\n
                        proxy_set_header Host \\$$host;\\n
                        proxy_set_header X-Real-IP \\$$remote_addr;\\n
                        proxy_set_header X-Forwarded-For \\$$proxy_add_x_forwarded_for;\\n
                        if (\\$$http_referer ~* \\\"\\/airflow\\/*.*\\\") {\\n
                            set \\$$is_airflow \\\"A\\\";\\n
                        }\\n
                        if (\\$$request_uri !~* ^\\/airflow\\/.*) {\\n
                            set \\$$is_airflow \\\"\\$${is_airflow}B\\\";\\n
                        }\\n
                        if (\\$$is_airflow ~* AB) { \\n
                            rewrite ^\\/*(.*) \\/airflow\\/\\$$1 permanent;\\n
                        }\\n
                        if (\\$$http_referer ~* \\\".*\\/flower\\/*.*\\\") {\\n
                            set \\$$is_flower \\\"A\\\";\\n
                        }\\n
                        if (\\$$request_uri !~* ^\\/flower\\/.*) {\\n
                            set \\$$is_flower \\\"\\$${is_flower}B\\\";\\n
                        }\\n
                        if (\\$$is_flower = AB) { \\n
                            rewrite ^\\/*(.*) \\/flower\\/\\$$1 permanent;\\n
                        }\\n
                        if (\\$$http_referer ~* \\\".*\\/visualizer\\/*.*\\\") {\\n
                            set \\$$is_visualizer \\\"A\\\";\\n
                        }\\n
                        if (\\$$request_uri !~* ^\\/visualizer\\/.*) {\\n
                            set \\$$is_visualizer \\\"\\$${is_visualizer}B\\\";\\n
                        }\\n
                        if (\\$$is_visualizer = AB) { \\n
                            rewrite ^\\/*(.*) \\/visualizer\\/\\$$1 permanent;\\n
                        }\\n
                        if (\\$$http_referer ~* \\\".*\\/rabbitmq\\/*.*\\\") {\\n
                            set \\$$is_rabbitmq \\\"A\\\";\\n
                        }\\n
                        if (\\$$request_uri !~* ^\\/rabbitmq\\/.*) {\\n
                            set \\$$is_rabbitmq \\\"\\$${is_rabbitmq}B\\\";\\n
                        }\\n
                        if (\\$$is_rabbitmq = AB) { \\n
                            rewrite ^\\/*(.*) \\/rabbitmq\\/\\$$1 permanent;\\n
                        }\\n
                        location \\/ {\\n
                            rewrite . \\/airflow\\/admin\\/ permanent;\\n
                        }\\n
                        location ^~ \\/airflow\\/ {\\n
                            proxy_redirect http:\\/\\/\\$$host \\$$scheme:\\/\\/\\$$host;\\n
                            proxy_pass http:\\/\\/webserver:8080\\/;\\n
                        }\\n
                        location ^~ \\/flower\\/ {\\n
                            sub_filter_last_modified on;\\n
                            sub_filter_once off;\\n
                            sub_filter_types application\\/javascript;\\n
                            sub_filter \\\"url_prefix() +\\\" \\\"'\\/flower' +\\\";\\n
                            proxy_redirect http:\\/\\/\\$$host \\$$scheme:\\/\\/\\$$host;\\n
                            proxy_pass http:\\/\\/flower:5555\\/;\\n
                        }\\n
                        location ^~ \\/visualizer\\/ {\\n
                            proxy_redirect http:\\/\\/\\$$host \\$$scheme:\\/\\/\\$$host;\\n
                            proxy_pass http:\\/\\/visualizer:8080\\/;\\n
                        }\\n
                        location ^~ \\/rabbitmq\\/ {\\n
                            proxy_pass http:\\/\\/rabbitmq:15672\\/;\\n
                            proxy_redirect off;\\n
                        }\\n
                    }\\n
                }/\" /etc/nginx/nginx.conf;
            fi &&
            unset BASIC_AUTH_PASSWORD &&
            unset BASIC_AUTH_USERNAME &&
            unset SSL_CERTIFICATE &&
            nginx-debug -g \"daemon off;\" 2>&1"
        secrets:
            - basic_auth_username
            - basic_auth_password
            - ssl_certificate
            - ssl_certificate_key

secrets:
    basic_auth_username:
        external: true
    basic_auth_password:
        external: true
    ssl_certificate:
        external: true
    ssl_certificate_key:
        external: true

networks:
    default:
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/16
